/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.proyect.Vistas.VentanasListar;

import org.proyect.Vistas.Ventana;
/**
 *
 * @author manue
 */
public class VentanaRegistroEmpleados extends javax.swing.JFrame implements Ventana {

    /**
     * Creates new form VentanaRegistroEmpleados
     */
    @Override
    public void iniciar() {
        this.setTitle("Registro Empleados");
        this.setVisible(true);// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void cerrar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public VentanaRegistroEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBusqueda = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCBBuscar = new javax.swing.JComboBox<>();
        jCBMetodo = new javax.swing.JComboBox<>();
        jTFIngresar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrdenada = new javax.swing.JTable();
        jButtonListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBAlgoritmo = new javax.swing.JComboBox<>();
        jCBCriterio = new javax.swing.JComboBox<>();
        jButtonOrdenar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        PanelFondo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 22)); // NOI18N
        PanelFondo.setMaximumSize(new java.awt.Dimension(800, 600));
        PanelFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        PanelFondo.setPreferredSize(new java.awt.Dimension(800, 600));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(57, 62, 89));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Email", "Departamento"
            }
        ));
        jTableBusqueda.setMaximumSize(new java.awt.Dimension(288, 51));
        jTableBusqueda.setMinimumSize(new java.awt.Dimension(288, 51));
        jTableBusqueda.setPreferredSize(new java.awt.Dimension(288, 51));
        jScrollPane3.setViewportView(jTableBusqueda);

        panel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 199, 288, 51));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar por:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Metodo");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jCBBuscar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jCBBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dni", "Nombre" }));
        panel1.add(jCBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 22, 170, 29));

        jCBMetodo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jCBMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secuencial ", "Binaria " }));
        panel1.add(jCBMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 101, 170, 30));

        jTFIngresar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        panel1.add(jTFIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 62, 170, 29));

        jButtonBuscar.setBackground(new java.awt.Color(130, 217, 217));
        jButtonBuscar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(57, 62, 89));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 146, 160, 40));

        PanelFondo.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 310, 346, 270));

        Titulo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(57, 62, 89));
        Titulo.setText("REGISTRO EMPLEADOS");
        Titulo.setAlignmentX(23.0F);
        PanelFondo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 18, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(380, 220));

        jTableOrdenada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Email", "Departamento"
            }
        ));
        jTableOrdenada.setPreferredSize(new java.awt.Dimension(380, 220));
        jScrollPane1.setViewportView(jTableOrdenada);

        PanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jButtonListar.setBackground(new java.awt.Color(57, 62, 89));
        jButtonListar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 22)); // NOI18N
        jButtonListar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListar.setText("LISTAR");
        jButtonListar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonListar.setPreferredSize(new java.awt.Dimension(167, 51));
        PanelFondo.add(jButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 29, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 62, 89));
        jLabel1.setText("Registro Ordenado:");
        PanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 310, -1, -1));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(380, 200));

        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Email", "Departamento"
            }
        ));
        jScrollPane2.setViewportView(jTablePrincipal);

        PanelFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel2.setText("Algoritmo:");
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 129, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel3.setText("Criterio:");
        PanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jCBAlgoritmo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jCBAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bubblesort ", "Selectionsort ", "Insertionsort ", "Quicksort ", "Shellsort ", "Mergesort " }));
        PanelFondo.add(jCBAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 170, 29));

        jCBCriterio.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jCBCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dni", "Nombre", "Departamento" }));
        PanelFondo.add(jCBCriterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 170, 29));

        jButtonOrdenar.setBackground(new java.awt.Color(57, 62, 89));
        jButtonOrdenar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButtonOrdenar.setForeground(new java.awt.Color(130, 217, 217));
        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelFondo.add(jButtonOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 231, 160, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel7.setText("Todos los derechos reservados @grupo3");
        PanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel Titulo;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonListar;
    public javax.swing.JButton jButtonOrdenar;
    public javax.swing.JComboBox<String> jCBAlgoritmo;
    public javax.swing.JComboBox<String> jCBBuscar;
    public javax.swing.JComboBox<String> jCBCriterio;
    public javax.swing.JComboBox<String> jCBMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jTFIngresar;
    public javax.swing.JTable jTableBusqueda;
    public javax.swing.JTable jTableOrdenada;
    public javax.swing.JTable jTablePrincipal;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
